# This file is a template, and might need editing before it works on your project.

before_script:
  - make env

build-1.10:
  image: newpagecommunity/sourcemod-builder:latest
  stage: build
  variables:
    SOURCEMOD_VERSION: "1.10"
  script:
    - make build
  only:
    - master
  artifacts:
    expire_in: 1 week
    paths:
      - compiled/*
